name: Run Bilyoner Script

on:
  push:
    branches:
      - main  # veya 'master' – senin repo ana dalın hangisiyse
  workflow_dispatch:  # elle tetikleme imkanı verir

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: |
          python Bilyoner.py

     - name: Upload generated M3U file

  if: success()
  uses: actions/upload-artifact@v4
  with:
    name: bilyoner-kanallar
    path: bilyoner_kanallar.m3u

