name: Generate IPTV M3U Playlist

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install requests

    - name: Run IPTV script
      run: python Mac2M3uPlaylist.py

    - name: List output directory files
      run: ls -la output

    - name: Upload M3U artifact
      uses: actions/upload-artifact@v4
      with:
        name: m3u-playlist
        path: output/Mac2M3uPlaylist.m3u
